In [143]:
import pandas as pd

In [144]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [145]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [147]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [148]:
df.describe(exclude=['int64', 'float64']).T

                       count unique             top  freq
Gender                  3900      2            Male  2652
Item Purchased          3900     25          Blouse   171
Category                3900      4        Clothing  1737
Location                3900     50         Montana    96
Size                    3900      4               M  1755
Color                   3900     25           Olive   177
Season                  3900      4          Spring   999
Subscription Status     3900      2              No  2847
Shipping Type           3900      6   Free Shipping   675
Discount Applied        3900      2              No  2223
Promo Code Used         3900      2              No  2223
Payment Method          3900      6          PayPal   677
Frequency of Purchases  3900      7  Every 3 Months   584

In [149]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [150]:
df[df['Review Rating'].isna()]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
38,39,29,Male,Dress,Clothing,37,Florida,M,Red,Winter,NaN,Yes,2-Day Shipping,Yes,Yes,44,Venmo,Every 3 Months
50,51,49,Male,Blouse,Clothing,28,Maryland,M,Red,Spring,NaN,Yes,Store Pickup,Yes,Yes,39,Debit Card,Bi-Weekly
80,81,19,Male,Sandals,Footwear,72,New York,XL,Blue,Summer,NaN,Yes,Store Pickup,Yes,Yes,24,Credit Card,Every 3 Months
96,97,32,Male,Gloves,Accessories,73,Delaware,S,Gold,Spring,NaN,Yes,Express,Yes,Yes,43,Venmo,Every 3 Months
262,263,37,Male,Pants,Clothing,40,Hawaii,M,Teal,Summer,NaN,Yes,Next Day Air,Yes,Yes,6,Debit Card,Annually
330,331,46,Male,Sweater,Clothing,51,North Dakota,M,Beige,Winter,NaN,Yes,Express,Yes,Yes,43,Venmo,Bi-Weekly
356,357,56,Male,Pants,Clothing,80,Nevada,L,Black,Spring,NaN,Yes,Standard,Yes,Yes,27,Cash,Weekly
383,384,50,Male,Sunglasses,Accessories,77,West Virginia,S,Magenta,Fall,NaN,Yes,Standard,Yes,Yes,6,PayPal,Quarterly
419,420,53,Male,Shorts,Clothing,91,Utah,S,Teal,Winter,NaN,Yes,Free Shipping,Yes,Yes,14,Credit Card,Every 3 Months
442,443,29,Male,Sunglasses,Accessories,69,Michigan,M,Olive,Fall,NaN,Yes,Store Pickup,Yes,Yes,31,Credit Card,Quarterly
452,453,45,Male,Pants,Clothing,45,Missouri,M,Violet,Summer,NaN,Yes,Express,Yes,Yes,39,PayPal,Fortnightly
460,461,64,Male,Shoes,Footwear,65,South Carolina,L,Teal,Summer,NaN,Yes,Store Pickup,Yes,Yes,27,Bank Transfer,Weekly
491,492,49,Male,Coat,Outerwear,69,Vermont,M,Silver,Summer,NaN,Yes,2-Day Shipping,Yes,Yes,24,Credit Card,Bi-Weekly
512,513,19,Male,Gloves,Accessories,49,New York,L,Peach,Winter,NaN,Yes,Next Day Air,Yes,Yes,2,Bank Transfer,Monthly
560,561,25,Male,Jewelry,Accessories,48,Louisiana,L,Red,Fall,NaN,Yes,Free Shipping,Yes,Yes,12,Debit Card,Annually
628,629,69,Male,Sweater,Clothing,85,Massachusetts,M,White,Fall,NaN,Yes,2-Day Shipping,Yes,Yes,29,Credit Card,Monthly
799,800,55,Male,Belt,Accessories,55,Nevada,L,Brown,Summer,NaN,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
829,830,42,Male,Socks,Clothing,57,Idaho,S,Silver,Spring,NaN,Yes,2-Day Shipping,Yes,Yes,14,Credit Card,Fortnightly
861,862,46,Male,Skirt,Clothing,100,Virginia,XL,Green,Spring,NaN,Yes,2-Day Shipping,Yes,Yes,35,Credit Card,Every 3 Months
888,889,49,Male,Scarf,Accessories,77,New Hampshire,S,Gold,Spring,NaN,Yes,Express,Yes,Yes,44,Cash,Annually
1072,1073,48,Male,Shorts,Clothing,92,Idaho,L,Gold,Fall,NaN,No,Express,Yes,Yes,34,Debit Card,Fortnightly
1109,1110,66,Male,Hoodie,Clothing,97,Oklahoma,L,Violet,Winter,NaN,No,Next Day Air,Yes,Yes,2,Venmo,Weekly
1124,1125,42,Male,Sweater,Clothing,20,Iowa,M,Orange,Spring,NaN,No,Express,Yes,Yes,40,Cash,Quarterly
1134,1135,62,Male,T-shirt,Clothing,81,Wisconsin,M,Brown,Summer,NaN,No,Express,Yes,Yes,2,Venmo,Every 3 Months
1151,1152,41,Male,Blouse,Clothing,86,Ohio,M,Gray,Spring,NaN,No,Express,Yes,Yes,24,Credit Card,Weekly
1176,1177,36,Male,Dress,Clothing,83,Oregon,M,Red,Winter,NaN,No,Free Shipping,Yes,Yes,39,PayPal,Quarterly
1189,1190,64,Male,Shirt,Clothing,97,Arkansas,XL,Teal,Summer,NaN,No,Free Shipping,Yes,Yes,28,Debit Card,Annually
1208,1209,20,Male,Boots,Footwear,100,Wisconsin,S,Red,Winter,NaN,No,2-Day Shipping,Yes,Yes,8,Debit Card,Annually
1220,1221,67,Male,Gloves,Accessories,64,Kentucky,M,Green,Winter,NaN,No,Express,Yes,Yes,36,Bank Transfer,Quarterly
1230,1231,25,Male,Hat,Accessories,80,Illinois,L,Brown,Spring,NaN,No,Standard,Yes,Yes,49,Venmo,Monthly
1247,1248,65,Male,T-shirt,Clothing,99,Virginia,M,Charcoal,Spring,NaN,No,Express,Yes,Yes,18,Venmo,Bi-Weekly
1292,1293,26,Male,Belt,Accessories,61,Kentucky,M,Maroon,Summer,NaN,No,Free Shipping,Yes,Yes,42,Bank Transfer,Annually
1313,1314,70,Male,Shoes,Footwear,28,Missouri,M,Lavender,Summer,NaN,No,Free Shipping,Yes,Yes,23,Credit Card,Bi-Weekly
1326,1327,40,Male,Shoes,Footwear,50,Texas,M,Indigo,Spring,NaN,No,Free Shipping,Yes,Yes,17,Cash,Monthly
1334,1335,46,Male,Coat,Outerwear,52,West Virginia,S,White,Spring,NaN,No,Store Pickup,Yes,Yes,12,Venmo,Monthly
1341,1342,26,Male,Hoodie,Clothing,27,Rhode Island,XL,Yellow,Fall,NaN,No,Standard,Yes,Yes,31,Bank Transfer,Quarterly
1370,1371,27,Male,Scarf,Accessories,67,Montana,L,Peach,Summer,NaN,No,2-Day Shipping,Yes,Yes,41,Bank Transfer,Every 3 Months

In [151]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [152]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [153]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.rename(columns={'purchase_amount_(usd)' : 'purchase_amount'}, inplace=True)

In [154]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [155]:
# New Column Age Group

labels = ['Young Adult', 'Adult', 'Middle_age', 'Senior']

df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [156]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle_age
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle_age
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle_age

In [157]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55   Middle_age
1   19  Young Adult
2   50   Middle_age
3   21  Young Adult
4   45   Middle_age
5   46   Middle_age
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57   Middle_age

In [158]:
df['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [159]:
# New Column Purchase Frequency Days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly' : 7,
    'Annually': 365,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Monthly': 30,
    'Every 3 Months': 90
}

df['purchace_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [160]:
df[['frequency_of_purchases', 'purchace_frequency_days']]

     frequency_of_purchases  purchace_frequency_days
0               Fortnightly                       14
1               Fortnightly                       14
2                    Weekly                        7
3                    Weekly                        7
4                  Annually                      365
...                     ...                      ...
3895                 Weekly                        7
3896              Bi-Weekly                       14
3897              Quarterly                       90
3898                 Weekly                        7
3899              Quarterly                       90

[3900 rows x 2 columns]

In [161]:
df[['discount_applied', 'promo_code_used']].sample(10)

     discount_applied promo_code_used
3809               No              No
2090               No              No
2761               No              No
83                Yes             Yes
2185               No              No
1249              Yes             Yes
1640              Yes             Yes
3661               No              No
395               Yes             Yes
3450               No              No

In [162]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [163]:
df.drop('promo_code_used', inplace=True,axis=1)

In [164]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchace_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle_age,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle_age,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle_age,365

In [165]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\saud\appdata\local\programs\python\python313\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\saud\appdata\local\programs\python\python313\lib\site-packages (2.0.44)
Requirement already satisfied: greenlet>=1 in c:\users\saud\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\saud\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.14.1)

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [166]:
from sqlalchemy import create_engine
username = 'postgres'
password = 'saud56'
host = 'localhost'
port = '5432'
database = 'customer_behavior'

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = 'customer'
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f'data loaded successfully in {table_name} in databse {database}')

data loaded successfully in customer in databse customer_behavior

In [167]:
username = 'root'
password = 'saud56'
host = 'localhost'
port = '3306'
database = 'customer_behavior'

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

table_name = 'customer'
df.to_sql(table_name, engine, if_exists="replace", index=False)

pd.read_sql("SELECT * FROM customer LIMIT 5", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchace_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle_age,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle_age,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle_age,365